### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by paride** [jeromerobert/pdfshuffler#14] opened 2018-09-29 15:54 UTC
The port to gtk3/python3 is a huge improvement for this great tool, it is really worth a release. Many distributions (e.g. Debian) normally package only "official" releases, so the new features won't make it in the next release if a version is not tagged.

**Comment by jeromerobert** [comment] 2018-09-29 23:52
See #9

I just e-mailed the original to known what are is plans

**Comment by jeromerobert** [comment] 2018-09-30 00:01
Duplicate of #9 (which I just reopened)

**Closed by jeromerobert** 2018-09-30 00:01 UTC
